### ISSUE TITLE
__route.py create wrong command to startup daemon

### ISSUE THREAD

**Issue by py0ker** [cnp3/ipmininet#100]
origin __route.py generate command 
### "zebra -f /tmp/zebra_as1ra.cfg -i /tmp/zebra_as1ra.pid -z /tmp/quagga_as1ra.api -u root -k"
the argument **"-k"** cannot be identified, and then the bgpd cannot startup
I use **[:-2]** to split the command string but it's a temporary method.
And, I use the latest ipmininet code

**Comment by jadinm** [comment]
Thank you for reporting :+1: 

I didn't observe this problem on FRRouting 7.1 but they might have removed the "-k" option in a recent release
Could you tell which version of FRRouting that you are using ?
You can know it by executing:
```sh
zebra -v
```

**Comment by py0ker** [comment]
thanks for your reply, I see my frr version is 7.5

**Comment by jadinm** [comment]
This should be fixed from commit 96f721f5998bb03b315582e8421b9a105fd5f1e6

Don't hesitate to reopen the issue if you are still experiencing it
