### ISSUE TITLE
How do I get link delay from the network state?

### ISSUE THREAD

**Issue by CavalryXD** [cnp3/ipmininet#103]
we can get the network state in IPMininet, the usage in [here](https://ipmininet.readthedocs.io/en/latest/topologydb.html) 
and if I set link delay in addLink() [related](https://ipmininet.readthedocs.io/en/latest/tc.html), How can I get this argument in TopologyDB? Thanks

**Comment by jadinm** [comment]
At the moment, it is not possible to export it through TopologyDB to the produced json
There is no particular to adding it, it would only require one more line there https://github.com/cnp3/ipmininet/blob/master/ipmininet/topologydb.py#L129

If you can access the IPNet object, you can already access that without using TopologyDB with
```python
net["your-node-name"].intf("your-interface-name").params.get('delay', -1)
```

**Comment by CavalryXD** [comment]
Thanks for your reply, It's a good idea and I use the interface in Mininet
`net.topo.linkInfo('node1', 'node2')`
It seems to figure out
