### ISSUE TITLE
Why traffic cann't be captured by wireshark?

### ISSUE THREAD

**Issue by VihanChou** [cnp3/ipmininet#111]
Why my wireshark cann't capture the traffic when I create a network by ipmininet and ping works well? Thanks for your help!!!!

**Comment by oliviertilmans** [comment]
Hi @VihanChou wireshark should work as-is.
Make sure you are running it from within a node's namespace, e.g., assuming there is a node named `r1` in your topology,
you can start wireshark inside that node by typing "r1 wireshark" inside the ipmininet cli. Note that it will only the links/interfaces connected to r1.

**Comment by VihanChou** [comment]
@oliviertilmans 
So appreciate!!!!!!
