### ISSUE TITLE
Can't open the srv6 example correctly.

### ISSUE THREAD

**Issue by VihanChou** [cnp3/ipmininet#112]
Sorry to interrupt. When I tried to start the srv6 case, the following error occurred. If possible, please help me solve the problem. Thank you very much

vihanchou@Ubuntu18:~/Desktop/SRv6$ sudo python -m ipmininet.examples --topo=ipv6_segment_routing

*** Adding Routers:
r1 r2 r3 r4 r5 r6 
*** Creating network
*** Adding hosts:
h1 h3 h4 h6 
*** Adding switches:

*** Adding links:
(h1, r1) (h3, r3) (h4, r4) (h6, r6) (r1, r2) (r1, r6) (r2, r3) (r2, r5) (r3, r4) (r4, r5) (r5, r6) 
*** Configuring hosts
h1 h3 h4 h6 
*** Found 17 broadcast domains
*** Allocating IPv4 addresses
*** Allocating IPv6 addresses
*** Starting controller

*** Starting 0 switches

*** Starting,  6 routers
r1 ospf6d configuration check failed [rcode: 1 ]
stdout:  
stderr: *** Error reading config: There is no such command.
*** Error occurred processing line 47, below:
  ospf6 router-id 192.168.11.2

Config checks failed, aborting!*** Removing excess controllers/ofprotocols/ofdatapaths/pings/noxes
killall controller ofprotocol ofdatapath ping nox_corelt-nox_core ovs-openflowd ovs-controllerovs-testcontroller udpbwtest mnexec ivs ryu-manager 2> /dev/null
killall -9 controller ofprotocol ofdatapath ping nox_corelt-nox_core ovs-openflowd ovs-controllerovs-testcontroller udpbwtest mnexec ivs ryu-manager 2> /dev/null
pkill -9 -f "sudo mnexec"
*** Removing junk from /tmp
rm -f /tmp/vconn* /tmp/vlogs* /tmp/*.out /tmp/*.log
*** Removing old X11 tunnels
*** Removing excess kernel datapaths
ps ax | egrep -o 'dp[0-9]+' | sed 's/dp/nl:/'
***  Removing OVS datapaths
ovs-vsctl --timeout=1 list-br
ovs-vsctl --timeout=1 list-br
*** Removing all links of the pattern foo-ethX
ip link show | egrep -o '([-_.[:alnum:]]+-eth[[:digit:]]+)'
ip link show
*** Killing stale mininet node processes
pkill -9 -f mininet:
*** Shutting down stale tunnels
pkill -9 -f Tunnel=Ethernet
pkill -9 -f .ssh/mn
rm -f ~/.ssh/mn/*
*** Cleanup complete.

**Comment by jadinm** [comment]
Hello,

Could you tell me which version of FRR you are using with the following command ?
```shell
$ zebra -v
```

And the version of ipmininet that you use with the following command ?
```shell
$ pip show ipmininet
```

Can you execute the examples `simple_ospf_network` and `simple_ospfv3_network` or does it raise the same issue ?

**Comment by VihanChou** [comment]
@jadinm  Hi ,Thanks for your reply and here is my terminal log


vihanchou@Ubuntu18:~/Desktop/SRv6$ zebra -v
zebra version 1.2.4
Copyright 1996-2005 Kunihiro Ishiguro, et al.
configured with:
	--build=aarch64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=${prefix}/lib/aarch64-linux-gnu --libexecdir=${prefix}/lib/aarch64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking --enable-exampledir=/usr/share/doc/quagga/examples/ --localstatedir=/run/quagga --sysconfdir=/etc/quagga --disable-watchquagga --with-libpam --enable-user=quagga --enable-group=quagga --enable-vty-group=quaggavty --enable-configfile-mask=0660 --enable-logfile-mask=0640 --enable-multipath=64 --libdir=/usr/lib/quagga CFLAGS=-g -O2 -fdebug-prefix-map=/build/quagga-FLrsys/quagga-1.2.4=. -fstack-protector-strong -Wformat -Werror=format-security CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2 CXXFLAGS=-g -O2 -fdebug-prefix-map=/build/quagga-FLrsys/quagga-1.2.4=. -fstack-protector-strong -Wformat -Werror=format-security FCFLAGS=-g -O2 -fdebug-prefix-map=/build/quagga-FLrsys/quagga-1.2.4=. -fstack-protector-strong FFLAGS=-g -O2 -fdebug-prefix-map=/build/quagga-FLrsys/quagga-1.2.4=. -fstack-protector-strong GCJFLAGS=-g -O2 -fdebug-prefix-map=/build/quagga-FLrsys/quagga-1.2.4=. -fstack-protector-strong LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now OBJCFLAGS=-g -O2 -fdebug-prefix-map=/build/quagga-FLrsys/quagga-1.2.4=. -fstack-protector-strong -Wformat -Werror=format-security OBJCXXFLAGS=-g -O2 -fdebug-prefix-map=/build/quagga-FLrsys/quagga-1.2.4=. -fstack-protector-strong -Wformat -Werror=format-security



vihanchou@Ubuntu18:~/Desktop/SRv6$ pip show ipmininet
Name: ipmininet
Version: 0.9
Summary: A mininet extension providing components to emulate IPnetworks running multiple protocols.
Home-page: https://github.com/cnp3/ipmininet
Author: Olivier Tilmans
Author-email: olivier.tilmans@uclouvain.be
License: GPLv2
Location: /home/vihanmy/anaconda3/envs/python369/lib/python3.6/site-packages
Requires: mininet, ipaddress, mako, setuptools
Required-by:

**Comment by jadinm** [comment]
Ok so your problem is that you are using Quagga and not FRR

The version of ipmininet 0.9 supports FRR 7.5 but not Quagga
There are slight differences in the configuration files and this is one of them

**Comment by VihanChou** [comment]
Thanks for your help!
