### ISSUE TITLE
Does ipmininet  available for both SDN(by openflow ) and SRv6?

### ISSUE THREAD

**Issue by VihanChou** [cnp3/ipmininet#113]
Is there any switching device in ipmininet that supports both openflow and srv6? In other words, if the switching device detects srv6 packets, it will forward them by segment routing, and when it detects other packets, it will forward them by openflow policy. Does the switch or router of ipmininet support such a function? I'm looking forward to your reply. Thank you

**Comment by jadinm** [comment]
No, we don't have this kind of abstraction in IPMininet

**Comment by VihanChou** [comment]
Thanks a lot
