### ISSUE TITLE
Please create a new release of VM

### ISSUE THREAD

**Issue by ldb** [cnp3/ipmininet#119]
I am using the provided [VM image](https://ipmininet.readthedocs.io/en/latest/install.html#virtual-machine) to work with IPMininet, however, when trying to use the NetworkCapture Overlay, it's not working, as the latest release 1.0 was created before this overlay was included, and no release has been cut since.

**Comment by jadinm** [comment]
Ok, there is a new release of IPMininet and its VM image now
