### ISSUE TITLE
SSHd test blocks

### ISSUE THREAD

**Issue by jadinm** [cnp3/ipmininet#22]
I tried to run the test with fulltrace (`sudo python setup.py test --addopts "ipmininet/tests/test_sshd.py --fulltrace"`). The test still gets stuck:
[test_sshd_result.txt](https://github.com/cnp3/ipmininet/files/3068415/test_sshd_result.txt)

_Originally posted by @butjar in https://github.com/cnp3/ipmininet/pull/17#issuecomment-482081259_

**Comment by butjar** [comment]
Do the logs help or should I step in with pdb ?

**Comment by jadinm** [comment]
It seems to be in the Mininet cleanup code but I really don't see why it would be blocked so long there.
I guess that doing ``mn -c`` doesn't block?

I can try to install the same Mininet version as yours.
Maybe it will help to reproduce the bug on my VM.
Which one is it?

Otherwise, yes, using pdb might give better information on the issue.

**Comment by jadinm** [comment]
If you replace the ``cleanup()`` call in ``ipmininet/test/test_sshd.py`` by ``pass``, does the test succeed?

Afterwards, you might need to call ``sudo python -m ipmininet.clean``, the equivalent of ``mn -c`` for IPMininet to clean remaining processes.

**Comment by jadinm** [comment]
@butjar Actually I might have a lead...

Could you check your /etc/shadow file and tell me if there is the line with the root user of your VM starts with "root:!" or with "root:*"?
If you see the first string, it means that the root account is locked and by default sshd won't allow you to login to the account (unless UsePAM is set to 'yes').

Moreover, there is an issue in the test that makes it loop forever if the ssh command fails.

So this could explain why the test takes forever in your VM while it does not in mine.

**Comment by butjar** [comment]
> If you replace the `cleanup()` call in `ipmininet/test/test_sshd.py` by `pass`, does the test succeed?
> 
> Afterwards, you might need to call `sudo python -m ipmininet.clean`, the equivalent of `mn -c` for IPMininet to clean remaining processes.

Seems not to be in cleanup. After removing the cleanup,

``` diff
--- a/ipmininet/tests/test_sshd.py
+++ b/ipmininet/tests/test_sshd.py
@@ -32,4 +32,5 @@ def test_sshd_example():

         net.stop()
     finally:
-        cleanup()
+       pass
+        #cleanup()
```
the test didn't come back either (should be finished roughly in about 1.5 min).

I guess the test does not come back because you are not incrementing `t`:
``` diff
diff --git a/ipmininet/tests/test_sshd.py b/ipmininet/tests/test_sshd.py
index ece2e6e..f57844c 100644
--- a/ipmininet/tests/test_sshd.py
+++ b/ipmininet/tests/test_sshd.py
@@ -27,6 +27,7 @@ def test_sshd_example():
         t = 0
         while t < 60 and net["r1"].popen(cmd.split(" ")).wait() != 0:
             time.sleep(0.5)
+            t=t+1
         p = net["r1"].popen(cmd.split(" "))
         assert p.wait() == 0, "Cannot connect with SSH to the router"
```
The test fails with:
```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    @require_root
    def test_sshd_example():
        try:
            net = IPNet(topo=SSHTopo())
            net.start()

            ssh_key = None
            with open("/tmp/sshd_r2.cfg") as fileobj:
                for line in fileobj:
                    if "AuthorizedKeysFile" in line:
                        ssh_key = line.split(" ")[1].split(".")[0]
            assert ssh_key is not None, "No authorized SSH key found in the configuration"
            assert os.path.isfile(ssh_key), "Cannot find key file at %s" % ssh_key

        import pdb; pdb.set_trace()
            ip = net["r2"].intf("r2-eth0").ip
            cmd = "ssh -oStrictHostKeyChecking=no -oConnectTimeout=1 -i %s %s ls" % (ssh_key, ip)
            t = 0
            while t < 60 and net["r1"].popen(cmd.split(" ")).wait() != 0:
>               time.sleep(0.5)
E               AssertionError: Cannot connect with SSH to the router
E               assert 255 == 0
E                +  where 255 = <bound method Popen.wait of <subprocess.Popen object at 0x7f68eb7a1690>>()
E                +    where <bound method Popen.wait of <subprocess.Popen object at 0x7f68eb7a1690>> = <subprocess.Popen object at 0x7f68eb7a1690>.wait

ipmininet/tests/test_sshd.py:30: AssertionError
```

I will check now if `/etc/shadow ` is  the root cause.

**Comment by butjar** [comment]
> @butjar Actually I might have a lead...
> 
> Could you check your /etc/shadow file and tell me if there is the line with the root user of your VM starts with "root:!" or with "root:*"?
> If you see the first string, it means that the root account is locked and by default sshd won't allow you to login to the account (unless UsePAM is set to 'yes').
> 
> Moreover, there is an issue in the test that makes it loop forever if the ssh command fails.
> 
> So this could explain why the test takes forever in your VM while it does not in mine.

Yes, thats the issue. After changing:
```
1c1
< root:!:17999:0:99999:7:::
---
> root:*:17999:0:99999:7:::
```
The test passes.

**Comment by jadinm** [comment]
Thanks a lot!

I will update that when I have some time.
