### ISSUE TITLE
Getting errors while installing Ipmininet

### ISSUE THREAD

**Issue by spazwik** [cnp3/ipmininet#68]
I have been getting this particular issue every time I try to install IPmininet

![ScreenShot_20200128223129](https://user-images.githubusercontent.com/10704857/73307796-34793700-421f-11ea-9847-d058a73bc446.png)

**Comment by jadinm** [comment]
Indeed, the recent versions of pip refuse that.
The package in question is Mininet that is not hosted on PyPI.

To install IPMininet, you should do so by using the commands on https://ipmininet.readthedocs.io/en/latest/install.html#manual-installation
